// Code generated by wingman-store, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/agui2200/wingman-store/examples/basic/store/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
