// Code generated by wingman-store, DO NOT EDIT.

package store

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
}
